//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int Id { get; set; }
        public string Tel_no { get; set; }
        public string adress { get; set; }
        public string email { get; set; }
        public string resim1 { get; set; }
        public string resim2 { get; set; }
        public string ad { get; set; }
        public string aciklama { get; set; }
    }
}
