//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int Id { get; set; }
        public string siparis_veren_user { get; set; }
        public Nullable<System.DateTime> siparis_tarihi { get; set; }
        public string siparis_listesi { get; set; }
        public string Sipars_adresi { get; set; }
        public string Siparis_telno { get; set; }
        public string siparis_email { get; set; }
        public string siparis_postakodu { get; set; }
    }
}
