//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public string urun_adi { get; set; }
        public string urun_aciklamasi { get; set; }
        public string urun_stok { get; set; }
        public string urun_Tarihi { get; set; }
        public string urun_fiyati { get; set; }
        public string urun_aktifmi { get; set; }
        public string urun_resmi { get; set; }
        public string urun_resmi2 { get; set; }
    }
}
