//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string k_adi { get; set; }
        public string k_sifre { get; set; }
        public string k_email { get; set; }
        public Nullable<int> k_IsAdmin { get; set; }
        public string k_sepet { get; set; }
        public string k_telno { get; set; }
        public string k_adress { get; set; }
    }
}
